version: "3"
services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  backend:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: release
      APP_ENV: ${APP_ENV}
    depends_on:
      - postgres
      - redis
