version: "3"
services:
  redis:
    image: redis:6
    ports:
      - "5432:5432"
  postgres:
    image: postgres:14
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_ENV: ${APP_ENV}
    depends_on:
      - postgres
      - redis
